version: '3.6'
services:
  mariadb:
    build: ./Database
    networks:
    - rpll
    volumes:
    - ./Database/patches:/docker-entrypoint-initdb.d
    - rpll_mariadb:/var/lib/mysql
    environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=vagrant
    - MYSQL_ROOT_PASSWORD=vagrant
    - TZ=Europe/Amsterdam
  backend:
    depends_on:
    - mariadb
    build: ./Backend
    networks:
    - rpll
    volumes:
    - rpll_backend_storage:/Storage
    environment:
    - MYSQL_URL=mysql://root:vagrant@mariadb/main
    - ROCKET_DATABASES={main={url="mysql://root:vagrant@mariadb/main"}}
    - SMTP_DNS=127.0.0.1:25
    - HOST=legacyplayers.com
    - MODEL_GENERATOR=http://localhost:5555
    - INSTANCE_STORAGE_PATH=/Storage
  webclient:
    build: ./Webclient
    networks:
    - rpll
  reverse-proxy:
    build: ./ReverseProxy
    networks:
    - rpll
    ports:
    - '1234:80'
#  traefik:
#    image: traefik:latest
#    command: --api.insecure=true --providers.docker
#    networks:
#    - rpll
#    ports:
#      - 443:443
#      - 8081:8081
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  rpll_mariadb:
  rpll_backend_storage:

networks:
  rpll:
